[package]
name = "rust_root_pkg_a_fixture"
version = "0.5.0"

[dependencies]
serde = { workspace = true }
rust_root_pkg_b_fixture = { workspace = true }
rust_root_pkg_c_fixture = { workspace = true }

[dev-dependencies]
rust_root_pkg_d_fixture = { workspace = true }

[target."cfg(windows)".dependencies]
rust_root_pkg_g_fixture = { workspace = true }
