version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "__fixtures__/**"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "__fixtures__/**"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
