[package]
name = "rust_pkg_a_fixture"
version = "0.5.0"

[dependencies]
serde = "1.0"

  [dependencies.ffi]
  package = "rust_pkg_b_fixture"
  path = "../pkg-b"
  version = "0.8.8"

[target."cfg(unix)".dependencies]
ffi-unix = { package = "rust_pkg_b_fixture", version = "0.8.8", path = "../pkg-b" }
