[package]
name = "tauri-api"
version = "0.5.1"
authors = "test"
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = ["test/fixture/**"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
dirs = "2.0.2"
ignore = "0.4.16"
zip = "0.5.5"
tempdir = "0.3"
semver = "0.10"
tempfile = "3"
either = "1.5.3"
tar = "0.4"
flate2 = "1"
anyhow = "1.0.31"
thiserror = "1.0.19"
rand = "0.7"
nfd = "0.0.4"
attohttpc = {version = "0.13.0", features=["json", "form" ]}
http = "0.2"
tauri-utils = {version = "0.5", path = "../tauri-utils"}

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
totems = "0.2.7"