[package]
name = "tauri-updater"
version = "0.4.2"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@tauri.studio>", "Daniel Thompson-Yvetot <denjell@sfosc.org>", "Tensor Programming <tensordeveloper@gmail.com>"]
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Updater for Tauri"
edition = "2018"
exclude = ["test/fixture/**"]

[dependencies]
attohttpc = {version = "0.10.1", features=["json", "compress" ]}
# pbr = "1"
serde_json = "1.0"
serde = "1.0"
zip = "0.5.3"
tempdir = "0.3"
tauri-api = { version = "0.5", path = "../tauri-api" }
tauri-utils = { version = "0.5", path = "../tauri-utils" }
anyhow = "1.0.31"
thiserror = "1.0.19"
