[package]
name = "covector-toml"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
toml_edit = { version = "0.21", features = ["serde"] }
wasm-bindgen = "0.2"
js-sys = "0.3.66"
