name: covector preview
on: pull_request

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run pkg -w action
      - name: covector preview
        uses: ./packages/action
        id: covector
        with:
          command: preview
      - name: dump covector output
        env:
          COVECTOR_CONTEXT: ${{ toJson(steps.covector) }}
        run: echo "$COVECTOR_CONTEXT"
