name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn workspace action build
      - name: covector status
        uses: ./packages/action
        with:
          command: 'status'
      - name: covector version
        uses: ./packages/action
        id: covector
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          command: 'version'
