name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: yarn
      - run: yarn workspace action build
      - name: covector status
        uses: ./packages/action
        with:
          command: 'status'
      - name: covector publish
        uses: ./packages/action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'publish'
          createRelease: true
          draft: true
