name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: yarn
      - run: yarn build
      - run: yarn workspace action pkg
      - name: covector status
        uses: ./packages/action
        id: covector
        with:
          command: 'status'
      - name: dump covector output
        env:
          COVECTOR_CONTEXT: ${{ toJson(steps.covector) }}
        run: echo "$COVECTOR_CONTEXT"
