name: covector
on: pull_request

jobs:
  status:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run pkg -w action
      - name: covector status
        uses: ./packages/action
        id: covector
        with:
          command: "status"
      - name: dump covector output
        env:
          COVECTOR_CONTEXT: ${{ toJson(steps.covector) }}
        run: echo "$COVECTOR_CONTEXT"
      - name: version dry run directly
        run: node ./packages/covector/bin/covector.js version --dry-run
      - run: git log --reverse --format="%h %H %as %s" .changes/upgrade-to-effection-v2.md

  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run pkg -w action
      - name: covector preview
        uses: ./packages/action
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: preview
      - name: dump covector output
        env:
          COVECTOR_CONTEXT: ${{ toJson(steps.covector) }}
        run: echo "$COVECTOR_CONTEXT"
