name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - name: covector build
        uses: ./packages/action
        with:
          command: 'build'
      - name: covector status
        uses: ./packages/action
        with:
          command: 'status'
      - name: covector publish
        uses: ./packages/action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'publish'
