name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: covector status
        uses: ./packages/action
        id: covector
        with:
          command: 'build'
      - name: covector status
        uses: ./packages/action
        id: covector
        with:
          command: 'status'
      - name: dump output
        env:
          COVECTOR_DUMP: ${{ toJson(steps.covector) }}
        run: echo "$COVECTOR_DUMP"
