name: covector status
on: [pull_request]

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - name: covector build
        uses: ./packages/action
        with:
          command: 'build'
      - name: covector status
        uses: ./packages/action
        with:
          command: 'status'
      - name: covector version
        uses: ./packages/action
        id: covector
        with:
          command: 'version'
      - name: Dump covector context
        env:
          JOB_CONTEXT: ${{ toJson(steps.covector.outputs.change) }}
        run: echo "$JOB_CONTEXT"