name: covector version or publish
on:
  push:
    branches:
    - main

jobs:
  covector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
      - run: yarn
      - name: covector build
        uses: ./packages/action
        with:
          command: 'build'
      - name: covector version-or-publish
        uses: ./packages/action
        id: covector
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          command: 'version-or-publish'
      - name: create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          title: "Publish New Versions"
          labels: "version updates"
          branch: "release"
          body: ${{ steps.covector.outputs.change }}
